-- Run this in Supabase SQL Editor
ALTER TABLE materials ADD COLUMN IF NOT EXISTS category TEXT DEFAULT '';
ALTER TABLE materials ADD COLUMN IF NOT EXISTS unit TEXT DEFAULT 'piezas';
ALTER TABLE materials ADD COLUMN IF NOT EXISTS location TEXT DEFAULT '';
ALTER TABLE materials ADD COLUMN IF NOT EXISTS observations TEXT DEFAULT '';
ALTER TABLE materials ADD COLUMN IF NOT EXISTS cantidad INTEGER DEFAULT 0;
ALTER TABLE materials ADD COLUMN IF NOT EXISTS umbral INTEGER DEFAULT 0;
ALTER TABLE movements ADD COLUMN IF NOT EXISTS observation TEXT DEFAULT '';
